"""add invoices and invoice_items tables

Revision ID: 1c90358a3b6c
Revises: ccfd9a8fd57e
Create Date: 2025-11-21 19:35:57.961586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c90358a3b6c'
down_revision: Union[str, None] = 'ccfd9a8fd57e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_code', sa.String(length=64), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('buyer_name', sa.String(length=128), nullable=False),
    sa.Column('buyer_address', sa.String(length=256), nullable=True),
    sa.Column('total_base', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_code'], ['tenants.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_code', 'invoice_number', name='uq_invoice_number_per_tenant')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_item_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_item_unit_price_nonneg'),
    sa.CheckConstraint('vat_rate >= 0', name='ck_item_vat_rate_nonneg'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_cash_entries_tenant_date', table_name='cash_entries')
    op.drop_constraint('cash_entries_tenant_code_fkey', 'cash_entries', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cash_entries_tenant_code_fkey', 'cash_entries', 'tenants', ['tenant_code'], ['code'], ondelete='CASCADE')
    op.create_index('ix_cash_entries_tenant_date', 'cash_entries', ['tenant_code', 'entry_date'], unique=False)
    op.drop_table('invoice_items')
    op.drop_table('invoices')
    # ### end Alembic commands ###
