"""fix cash_entries.id to be identity/autoincrement

Revision ID: fix_cash_id_identity_20250820
Revises: aa68d85d25cb
Create Date: 2025-08-20 00:00:00
"""
from alembic import op


# IDs
revision = "fix_cash_id_identity_20250820"
down_revision = "aa68d85d25cb"
branch_labels = None
depends_on = None


def upgrade():
    # Postgres: dodaj IDENTITY na postojeću kolonu id (ako već nema)
    op.execute("""
        DO $$
        BEGIN
            -- Ako kolona već NIJE identity, dodaj identity BY DEFAULT
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns c
                JOIN pg_catalog.pg_class t ON t.relname = c.table_name
                JOIN pg_catalog.pg_namespace n ON n.oid = t.relnamespace
                WHERE c.table_name = 'cash_entries'
                  AND c.column_name = 'id'
                  AND c.identity_generation IS NOT NULL
                  AND n.nspname = 'public'
            ) THEN
                ALTER TABLE public.cash_entries
                    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END
        $$;
    """)


def downgrade():
    # Vrati nazad: ukloni identity sa kolone id (opcionalno)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM information_schema.columns c
                JOIN pg_catalog.pg_class t ON t.relname = c.table_name
                JOIN pg_catalog.pg_namespace n ON n.oid = t.relnamespace
                WHERE c.table_name = 'cash_entries'
                  AND c.column_name = 'id'
                  AND c.identity_generation IS NOT NULL
                  AND n.nspname = 'public'
            ) THEN
                ALTER TABLE public.cash_entries
                    ALTER COLUMN id DROP IDENTITY IF EXISTS;
            END IF;
        END
        $$;
    """)
