"""ensure id is BIGINT and has generator on cash_entries.id"""

from alembic import op
import sqlalchemy as sa

# Revision identifiers, used by Alembic.
revision = "b6a5c2a8c9f1"
down_revision = "aa68d85d25cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1) Uvijek prvo forsiraj BIGINT tip (ako već nije)
    op.execute(
        """
        DO $$
        DECLARE
          col_type text;
        BEGIN
          SELECT data_type INTO col_type
          FROM information_schema.columns
          WHERE table_name = 'cash_entries' AND column_name = 'id';

          IF col_type IS NULL THEN
            RAISE EXCEPTION 'Column cash_entries.id not found';
          END IF;

          IF col_type NOT IN ('bigint', 'integer', 'smallint') THEN
            ALTER TABLE cash_entries
              ALTER COLUMN id TYPE BIGINT
              USING id::bigint;
          END IF;
        END$$;
        """
    )

    # 2) Probaj dodati IDENTITY; ako ne može (stari PG), fallback na sekvencu + DEFAULT nextval()
    op.execute(
        """
        DO $$
        BEGIN
          BEGIN
            ALTER TABLE cash_entries
              ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
          EXCEPTION
            WHEN duplicate_object THEN
              -- već postoji IDENTITY; ništa
              NULL;
            WHEN feature_not_supported THEN
              -- stariji PG: koristi sekvencu kao fallback
              IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'cash_entries_id_seq') THEN
                CREATE SEQUENCE cash_entries_id_seq OWNED BY cash_entries.id;
              END IF;
              ALTER TABLE cash_entries
                ALTER COLUMN id SET DEFAULT nextval('cash_entries_id_seq');
          END;
        END$$;
        """
    )


def downgrade() -> None:
    # Skini generator (IDENTITY ili DEFAULT) i potencijalnu sekvencu
    op.execute(
        """
        DO $$
        BEGIN
          BEGIN
            ALTER TABLE cash_entries
              ALTER COLUMN id DROP IDENTITY IF EXISTS;
          EXCEPTION
            WHEN undefined_object THEN
              NULL;
          END;

          ALTER TABLE cash_entries
            ALTER COLUMN id DROP DEFAULT;

          DROP SEQUENCE IF EXISTS cash_entries_id_seq;
        END$$;
        """
    )
