name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Postavi Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Pripremi .env za backend
        run: cp backend/.env.example backend/.env

      - name: Instaliraj dev dependency-je (pytest, httpx)
        run: pip install -r backend/requirements-dev.txt

      - name: Pokreni Docker Compose
        run: docker compose up -d

      - name: Sačekaj da API bude spreman
        run: |
          for i in {1..30}; do
            curl -fsS http://localhost:8000/health && break
            sleep 2
          done

      # ⬇️ OVO JE NOVI, POSEBAN KORAK
      - name: Pokreni migracije (alembic upgrade)
        run: docker compose exec -T api alembic upgrade head

      - name: Pokreni testove
        run: pytest -q backend/tests

      - name: Ispiši logove ako test padne
        if: failure()
        run: docker compose logs api db --no-color | tail -n 200

      - name: Ugasi stack
        if: always()
        run: docker compose down
